site_name: nerd Documentation
repo_url: https://github.com/edr-choi/nerd
repo_name: nerd
nav:
  - Home: index.md
  - Getting Started:
      - Create Samples: guides/create-samples.md
      - NMR Kinetics: guides/nmr-kinetics.md
      - Probe Timecourse: guides/probe-timecourse.md
      - Temperature Gradients: guides/tempgrad-fit.md
  - CLI Reference:
      - create: cli/create.md
      - nmr_create: cli/nmr_create.md
      - nmr_deg_kinetics: cli/nmr_deg_kinetics.md
      - nmr_add_kinetics: cli/nmr_add_kinetics.md
      - mut_count: cli/mut_count.md
      - probe_timecourse: cli/probe_timecourse.md
      - tempgrad_fit: cli/tempgrad_fit.md
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - include-markdown
markdown_extensions:
  - toc
  - admonition
  - codehilite
