run:
  output_dir: examples
  label: Salm_4U_v2_65C_rep1_subsample
  backend: remote
  remote:
    ssh:
      host: login.quest.northwestern.edu   # your login node
      user: ekc5108                        # your username
    slurm_config:
      partition: buyin
      account: b1044
      time: "00:30:13"                    # override run.time if needed
      memory: "12G"                        # override run.memory if needed
      cpus: 10                             # override run.cpus if needed
    remote_base_dir: /scratch/ekc5108/nerd/runner_test
    preamble:
      - 'echo "Activating environment on remote..."'
      - 'module load seqtk'  # required for derived child samples
      # - 'source ~/.bashrc; conda activate rna'
    stage_out:
      - samples/*/*_profile.txt
      - samples/*/*_profile.txtga
      - samples/*/*_parsed.mut
      - samples/*/*_parsed.mutga

mut_count:
  plugin: shapemapper
  tool:
    bin: /projects/b1044/Software/shapemapper2-2.3/shapemapper
    version: "2.3"
  derived_samples:
    - fourU_WT_65c_rep1_tp1__singlehit
  params:
    n_proc: 1
  # ShapeMapper options mapping
  amplicon: true                  # --amplicon
  dms_mode: true                  # --dms
  output_N7: true                 # --N7 --bypass_filters
  per_read_histograms: true         # --per-read-histograms
  output_parsed_mutations: true   # --output-parsed-mutations
  # Smoke test only: echo steps instead of running shapemapper
  dry_run: false